### ISSUE TITLE
setHeatpointSetpoint should be setHeatSetpoint

### ISSUE THREAD

**Issue by mdallau** [svrooij/evohome2mqtt#6]
When setting the temperature via MQTT you get an error evohomeClient.setHeatpointSetpoint is not a function. I researched this and it should be setHeatSetpoint instead of setHeatpointSetpoint.

**Comment by svrooij** [comment]
care to send an update? seems an easy fix?

**Comment by mdallau** [comment]
On  line 138, 146 and 154 in brigde.js you call setHeat**point**Setpoint of your @svrooij/evohome EvoHome client, but this function does not exist. The function name actually is setHeatSetpoint. See line 128 of evohome-client.ts in @svrooij/evohome.
