### ISSUE TITLE
Error Response

### ISSUE THREAD

**Issue by Hans-Zwiesel** [svrooij/evohome2mqtt#7]
Hi,
i installed it today (Version 1.1.1, node-js v10.23.2).
It looks great but i got an error response while loading data from evohome:

![grafik](https://user-images.githubusercontent.com/49147193/111141128-7419f400-8583-11eb-978c-30b50ae81cca.png)

Please, can you help me?

**Comment by svrooij** [comment]
It works here as expected.

- How long has it been running until you got this error?
- Have you checked the result in the mqtt server?
- What would you expect to happen?

## installing and starting the application.
![image](https://user-images.githubusercontent.com/1292510/111293783-f0770a80-8649-11eb-9a78-e234e0629790.png)

## Result in the mqtt server displayed with [mqtt explorer](http://mqtt-explorer.com/)
![image](https://user-images.githubusercontent.com/1292510/111294096-42b82b80-864a-11eb-8063-a166944bd19e.png)

**Comment by Hans-Zwiesel** [comment]
I removed evohome2mqtt and installed https://github.com/svrooij/evohome instead
then i copy from /root/node_modules/@svrooij/ the evohome folder to 
/opt/iobroker/node_modules/iobroker.javascript/node_modules/
in ioBroker i have to add in JS Instance the additional NPM module: evohome
Now it works very fine. Thanks
